select_column = [
	      "chr",
	      "position",
	      "ref",
	      "alt",
	      "qual",
	      "dataset",
	      "format_dp",
	      "format_gt",
	      "format_bd",
	      "format_gq",
	      "format_adall",
	      "format_ad",
]

[alias]
format_bd = "label"
format_dp = "coverage"